# Generated by Django 3.0.5 on 2021-03-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveIntegerField(choices=[('U', 'user'), ('M', 'moderator'), ('A', 'admin')], verbose_name='User_status'),
        ),
    ]
