# Generated by Django 3.0.5 on 2021-03-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210323_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('U', 'user'), ('M', 'moderator'), ('A', 'admin')], default='user', max_length=50, verbose_name='User_status'),
        ),
    ]
