# Generated by Django 3.0.5 on 2021-03-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210323_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('U', 'user'), ('M', 'moderator'), ('A', 'admin')], default='U', max_length=20, verbose_name='User_status'),
        ),
    ]
