# Generated by Django 3.0.5 on 2021-03-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210326_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
