# Generated by Django 3.0.5 on 2021-03-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210331_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default='BP0F8YC6NZ', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
