# Generated by Django 3.0.5 on 2021-04-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210331_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default='1SQX6V94HM', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
