# Generated by Django 3.0.5 on 2021-04-07 18:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210405_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('77060b6a-87d6-4e0d-96b1-d3a4b240b301'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
