# Generated by Django 3.0.5 on 2021-04-07 19:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210407_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('08a5693e-51bd-4bae-85c5-aaa831432720'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
