# Generated by Django 3.0.5 on 2021-04-07 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210407_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('274942df-415c-4742-8320-d729700fa537'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
